<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rm_mattigschauer"
 *
 * Auto generated by Extension Builder 2017-09-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Mattig Schauer Produkte',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Chris Rawk',
    'author_email' => 'ce@rawk.at',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-8.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
